title: 文柳轻扬的个人主页
page-top-title: Wen-Liuqingyang
top-section-bg-text: Be what you wanna be
home-subtitle: Wen-Liuqingyang&ensp;|&ensp;文柳轻扬
copyright-text: '&copy; Wen-Liuqingyang 2023-2025. All Rights Reserved.'
